/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_interface__Belief */

#ifndef _Included_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_interface__Belief
#define _Included_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_interface__Belief
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_interface__Belief
 * Method:    Sample_
 * Signature: (JI)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_interface_1_Belief_Sample_1
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_interface__Belief
 * Method:    Update_
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_interface_1_Belief_Update_1
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_interface__Belief
 * Method:    MakeCopy_
 * Signature: (J)Lde/dfki/asr/ajan/pluginsystem/mdpplugin/utils/POMDP/DESPOT/interface_/Belief;
 */
JNIEXPORT jobject JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_interface_1_Belief_MakeCopy_1
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
