/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_Connector_ROSConnector */

#ifndef _Included_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_Connector_ROSConnector
#define _Included_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_Connector_ROSConnector
#ifdef __cplusplus
extern "C" {
#endif
#undef de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_Connector_ROSConnector_TAG_ACTION
#define de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_Connector_ROSConnector_TAG_ACTION 4L
#undef de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_Connector_ROSConnector_NUM_LASER_DIRECTIONS
#define de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_Connector_ROSConnector_NUM_LASER_DIRECTIONS 8L
/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_Connector_ROSConnector
 * Method:    SetReading_
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_Connector_ROSConnector_SetReading_1
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_Connector_ROSConnector
 * Method:    GetReading_
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_Connector_ROSConnector_GetReading_1
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
