/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History */

#ifndef _Included_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History
#define _Included_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History
 * Method:    Add_
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History_Add_1
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History
 * Method:    RemoveLast_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History_RemoveLast_1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History
 * Method:    Action_
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History_Action_1
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History
 * Method:    Observation_
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History_Observation_1
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History
 * Method:    Size_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History_Size_1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History
 * Method:    Truncate_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History_Truncate_1
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History
 * Method:    LastAction_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History_LastAction_1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History
 * Method:    LastObservation_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History_LastObservation_1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History
 * Method:    Suffix_
 * Signature: (JI)Lde/dfki/asr/ajan/pluginsystem/mdpplugin/utils/POMDP/DESPOT/core/History;
 */
JNIEXPORT jobject JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_History_Suffix_1
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
