/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_MDP */

#ifndef _Included_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_MDP
#define _Included_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_MDP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_MDP
 * Method:    ComputeOptimalPoliciesUsingVIAndReturnPolicy
 * Signature: (J)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_MDP_ComputeOptimalPoliciesUsingVIAndReturnPolicy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_MDP
 * Method:    ComputeActionValue
 * Signature: (JJI)D
 */
JNIEXPORT jdouble JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_MDP_ComputeActionValue
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_MDP
 * Method:    policy
 * Signature: (J)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_MDP_policy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_MDP
 * Method:    ComputeOptimalPolicyUsingVI
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_dfki_asr_ajan_pluginsystem_mdpplugin_utils_POMDP_DESPOT_core_MDP_ComputeOptimalPolicyUsingVI
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
